#############################################################################
# Makefile for building: qtrpn
# Generated by qmake (3.1) (Qt 5.12.5)
# Project:  qtrpn.pro
# Template: app
# Command: /Qt/5.12.5/static/bin/qmake -o Makefile qtrpn.pro -config release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -ffunction-sections -fdata-sections -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -ffunction-sections -fdata-sections -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/Qt/5.12.5/static/include -I/Qt/5.12.5/static/include/QtWidgets -I/Qt/5.12.5/static/include/QtGui -I/Qt/5.12.5/static/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/Qt/5.12.5/static/mkspecs/linux-g++
QMAKE         = /Qt/5.12.5/static/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Qt/5.12.5/static/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Qt/5.12.5/static/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtrpn1.0.0
DISTDIR = /home/rob/qtrpn/.tmp/qtrpn1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,--gc-sections
LIBS          = $(SUBLIBS) /Qt/5.12.5/static/plugins/imageformats/libqgif.a /Qt/5.12.5/static/plugins/imageformats/libqicns.a /Qt/5.12.5/static/plugins/imageformats/libqico.a /Qt/5.12.5/static/plugins/imageformats/libqjpeg.a /usr/lib/x86_64-linux-gnu/libjpeg.so /Qt/5.12.5/static/plugins/imageformats/libqtga.a /Qt/5.12.5/static/plugins/imageformats/libqtiff.a /usr/lib/x86_64-linux-gnu/libtiff.so /Qt/5.12.5/static/plugins/imageformats/libqwbmp.a /Qt/5.12.5/static/plugins/imageformats/libqwebp.a /usr/lib/x86_64-linux-gnu/libwebp.so /usr/lib/x86_64-linux-gnu/libwebpdemux.so /Qt/5.12.5/static/lib/libQt5Widgets.a /Qt/5.12.5/static/lib/libQt5Gui.a /usr/lib/x86_64-linux-gnu/libpng16.so /Qt/5.12.5/static/lib/libqtharfbuzz.a /Qt/5.12.5/static/lib/libQt5Core.a -lm /usr/lib/x86_64-linux-gnu/libz.so /Qt/5.12.5/static/lib/libqtpcre2.a /usr/lib/x86_64-linux-gnu/libdl.so /usr/lib/x86_64-linux-gnu/libgthread-2.0.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		getcommandline2.cpp \
		timlibc2.cpp \
		tokenizec2.cpp \
		holidaycalc2.cpp \
		hpcalcc2.cpp \
		makesubst.cpp /home/rob/qtrpn/qtrpn_plugin_import.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		getcommandline2.o \
		timlibc2.o \
		tokenizec2.o \
		holidaycalc2.o \
		hpcalcc2.o \
		makesubst.o \
		qtrpn_plugin_import.o \
		moc_mainwindow.o
DIST          = /Qt/5.12.5/static/mkspecs/features/spec_pre.prf \
		/Qt/5.12.5/static/mkspecs/common/unix.conf \
		/Qt/5.12.5/static/mkspecs/common/linux.conf \
		/Qt/5.12.5/static/mkspecs/common/sanitize.conf \
		/Qt/5.12.5/static/mkspecs/common/gcc-base.conf \
		/Qt/5.12.5/static/mkspecs/common/gcc-base-unix.conf \
		/Qt/5.12.5/static/mkspecs/common/g++-base.conf \
		/Qt/5.12.5/static/mkspecs/common/g++-unix.conf \
		/Qt/5.12.5/static/mkspecs/qconfig.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3danimation.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dcore.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dextras.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dinput.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dlogic.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquick.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3drender.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3drender_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_bluetooth.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_charts.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_charts_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_concurrent.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_core.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_core_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_datavisualization.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_dbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_dbus_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_designer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_designer_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gamepad.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_glx_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gui.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gui_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_help.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_help_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_input_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_kms_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_location.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_location_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimedia.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_network.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_network_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_networkauth.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_nfc.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_nfc_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_opengl.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_opengl_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_openglextensions.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioning.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioning_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioningquick.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_printsupport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_purchasing.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qml.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qml_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmltest.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quick.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quick_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_repparser.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_repparser_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_script.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_script_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scripttools.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scxml.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scxml_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sensors.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sensors_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialport_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_service_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sql.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sql_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_svg.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_svg_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_testlib.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_testlib_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_texttospeech.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_uiplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_uitools.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_uitools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webchannel.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_websockets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_websockets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webview.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webview_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_widgets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_widgets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xml.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xml_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_evdevgamepad.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qgif.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qicns.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qico.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qminimal.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qnmbearer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsvg.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtaudio_alsa.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtga.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtiff.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmedia_pulse.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_geoclue2.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_counterplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qvnc.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwebgl.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwebp.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_scene2d.pri \
		/Qt/5.12.5/static/mkspecs/features/qt_functions.prf \
		/Qt/5.12.5/static/mkspecs/features/qt_config.prf \
		/Qt/5.12.5/static/mkspecs/linux-g++/qmake.conf \
		/Qt/5.12.5/static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Qt/5.12.5/static/mkspecs/features/exclusive_builds.prf \
		/Qt/5.12.5/static/mkspecs/features/toolchain.prf \
		/Qt/5.12.5/static/mkspecs/features/default_pre.prf \
		/Qt/5.12.5/static/mkspecs/features/resolve_config.prf \
		/Qt/5.12.5/static/mkspecs/features/default_post.prf \
		/Qt/5.12.5/static/mkspecs/features/warn_on.prf \
		/Qt/5.12.5/static/mkspecs/features/qt.prf \
		/Qt/5.12.5/static/mkspecs/features/gc_binaries.prf \
		/Qt/5.12.5/static/mkspecs/features/resources.prf \
		/Qt/5.12.5/static/mkspecs/features/moc.prf \
		/Qt/5.12.5/static/mkspecs/features/unix/opengl.prf \
		/Qt/5.12.5/static/mkspecs/features/uic.prf \
		/Qt/5.12.5/static/mkspecs/features/unix/thread.prf \
		/Qt/5.12.5/static/mkspecs/features/qmake_use.prf \
		/Qt/5.12.5/static/mkspecs/features/file_copies.prf \
		/Qt/5.12.5/static/mkspecs/features/testcase_targets.prf \
		/Qt/5.12.5/static/mkspecs/features/exceptions.prf \
		/Qt/5.12.5/static/mkspecs/features/yacc.prf \
		/Qt/5.12.5/static/mkspecs/features/lex.prf \
		qtrpn.pro mainwindow.h \
		macros.h \
		getcommandline2.h \
		timlibc2.h \
		tokenizec2.h \
		hpcalcc2.h \
		holidaycalc2.h \
		makesubst.h main.cpp \
		mainwindow.cpp \
		getcommandline2.cpp \
		timlibc2.cpp \
		tokenizec2.cpp \
		holidaycalc2.cpp \
		hpcalcc2.cpp \
		makesubst.cpp
QMAKE_TARGET  = qtrpn
DESTDIR       = 
TARGET        = qtrpn


first: all
####### Build rules

qtrpn: /Qt/5.12.5/static/lib/libQt5Widgets.a /Qt/5.12.5/static/lib/libQt5Gui.a /Qt/5.12.5/static/lib/libQt5Core.a ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtrpn.pro /Qt/5.12.5/static/mkspecs/linux-g++/qmake.conf /Qt/5.12.5/static/mkspecs/features/spec_pre.prf \
		/Qt/5.12.5/static/mkspecs/common/unix.conf \
		/Qt/5.12.5/static/mkspecs/common/linux.conf \
		/Qt/5.12.5/static/mkspecs/common/sanitize.conf \
		/Qt/5.12.5/static/mkspecs/common/gcc-base.conf \
		/Qt/5.12.5/static/mkspecs/common/gcc-base-unix.conf \
		/Qt/5.12.5/static/mkspecs/common/g++-base.conf \
		/Qt/5.12.5/static/mkspecs/common/g++-unix.conf \
		/Qt/5.12.5/static/mkspecs/qconfig.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3danimation.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dcore.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dextras.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dinput.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dlogic.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquick.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3drender.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_3drender_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_bluetooth.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_charts.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_charts_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_concurrent.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_core.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_core_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_datavisualization.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_dbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_dbus_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_designer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_designer_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gamepad.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_glx_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gui.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_gui_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_help.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_help_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_input_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_kms_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_location.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_location_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimedia.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_network.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_network_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_networkauth.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_nfc.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_nfc_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_opengl.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_opengl_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_openglextensions.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioning.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioning_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioningquick.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_printsupport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_purchasing.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qml.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qml_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmltest.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quick.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quick_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_repparser.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_repparser_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_script.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_script_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scripttools.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scxml.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_scxml_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sensors.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sensors_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialport_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_service_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sql.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_sql_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_svg.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_svg_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_testlib.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_testlib_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_texttospeech.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_uiplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_uitools.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_uitools_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webchannel.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_websockets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_websockets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webview.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_webview_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_widgets.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_widgets_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xml.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xml_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_assimpsceneimport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_evdevgamepad.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qconnmanbearer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qgif.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qicns.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qico.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qminimal.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qnmbearer.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsvg.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtaudio_alsa.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtga.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtiff.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmedia_pulse.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_geoclue.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_geoclue2.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_counterplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsocketcanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qttinycanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qvnc.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwebgl.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwebp.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri \
		/Qt/5.12.5/static/mkspecs/modules/qt_plugin_scene2d.pri \
		/Qt/5.12.5/static/mkspecs/features/qt_functions.prf \
		/Qt/5.12.5/static/mkspecs/features/qt_config.prf \
		/Qt/5.12.5/static/mkspecs/linux-g++/qmake.conf \
		/Qt/5.12.5/static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Qt/5.12.5/static/mkspecs/features/exclusive_builds.prf \
		/Qt/5.12.5/static/mkspecs/features/toolchain.prf \
		/Qt/5.12.5/static/mkspecs/features/default_pre.prf \
		/Qt/5.12.5/static/mkspecs/features/resolve_config.prf \
		/Qt/5.12.5/static/mkspecs/features/default_post.prf \
		/Qt/5.12.5/static/mkspecs/features/warn_on.prf \
		/Qt/5.12.5/static/mkspecs/features/qt.prf \
		/Qt/5.12.5/static/mkspecs/features/gc_binaries.prf \
		/Qt/5.12.5/static/mkspecs/features/resources.prf \
		/Qt/5.12.5/static/mkspecs/features/moc.prf \
		/Qt/5.12.5/static/mkspecs/features/unix/opengl.prf \
		/Qt/5.12.5/static/mkspecs/features/uic.prf \
		/Qt/5.12.5/static/mkspecs/features/unix/thread.prf \
		/Qt/5.12.5/static/mkspecs/features/qmake_use.prf \
		/Qt/5.12.5/static/mkspecs/features/file_copies.prf \
		/Qt/5.12.5/static/mkspecs/features/testcase_targets.prf \
		/Qt/5.12.5/static/mkspecs/features/exceptions.prf \
		/Qt/5.12.5/static/mkspecs/features/yacc.prf \
		/Qt/5.12.5/static/mkspecs/features/lex.prf \
		qtrpn.pro \
		/Qt/5.12.5/static/plugins/imageformats/libqgif.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqicns.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqico.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqjpeg.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqtga.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqtiff.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqwbmp.prl \
		/Qt/5.12.5/static/plugins/imageformats/libqwebp.prl \
		/Qt/5.12.5/static/lib/libQt5Widgets.prl \
		/Qt/5.12.5/static/lib/libQt5Gui.prl \
		/Qt/5.12.5/static/lib/libQt5Core.prl
	$(QMAKE) -o Makefile qtrpn.pro -config release
/Qt/5.12.5/static/mkspecs/features/spec_pre.prf:
/Qt/5.12.5/static/mkspecs/common/unix.conf:
/Qt/5.12.5/static/mkspecs/common/linux.conf:
/Qt/5.12.5/static/mkspecs/common/sanitize.conf:
/Qt/5.12.5/static/mkspecs/common/gcc-base.conf:
/Qt/5.12.5/static/mkspecs/common/gcc-base-unix.conf:
/Qt/5.12.5/static/mkspecs/common/g++-base.conf:
/Qt/5.12.5/static/mkspecs/common/g++-unix.conf:
/Qt/5.12.5/static/mkspecs/qconfig.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3danimation.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3danimation_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dcore.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dcore_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dextras.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dextras_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dinput.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dinput_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dlogic.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquick.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquick_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickextras.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickinput.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickrender.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3drender.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_3drender_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_bluetooth.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_charts.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_charts_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_concurrent.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_concurrent_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_core.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_core_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_datavisualization.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_dbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_dbus_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_designer.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_designer_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_edid_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_fb_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_gamepad.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_gamepad_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_glx_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_gui.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_gui_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_help.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_help_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_input_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_kms_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_location.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_location_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimedia.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimedia_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_network.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_network_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_networkauth.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_networkauth_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_nfc.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_nfc_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_opengl.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_opengl_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_openglextensions.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioning.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioning_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioningquick.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_printsupport.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_printsupport_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_purchasing.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_purchasing_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qml.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qml_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmltest.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qmltest_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quick.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quick_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickwidgets.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_remoteobjects.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_repparser.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_repparser_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_script.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_script_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_scripttools.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_scripttools_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_scxml.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_scxml_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_sensors.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_sensors_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialbus_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialport.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_serialport_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_service_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_sql.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_sql_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_svg.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_svg_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_testlib.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_testlib_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_texttospeech.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_theme_support_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_uiplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_uitools.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_uitools_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_webchannel.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_webchannel_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_websockets.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_websockets_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_webview.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_webview_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_widgets.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_widgets_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_xml.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_xml_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_assimpsceneimport.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_evdevgamepad.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_ibusplatforminputcontextplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qconnmanbearer.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qgif.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qicns.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qico.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qjpeg.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qlinuxfb.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qminimal.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qnmbearer.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsqlite.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsvg.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtaudio_alsa.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtga.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtiff.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmedia_pulse.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtpassthrucanbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtpeakcanbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_geoclue.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_geoclue2.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtposition_serialnmea.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_counterplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_iio-sensor-proxy.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtsocketcanbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qttinycanbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualcanbus.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_hangul.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_openwnn.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_pinyin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_tcime.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboard_thai.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qtvirtualkeyboardplugin.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qvnc.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwbmp.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwebgl.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qwebp.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_qxdgdesktopportal.pri:
/Qt/5.12.5/static/mkspecs/modules/qt_plugin_scene2d.pri:
/Qt/5.12.5/static/mkspecs/features/qt_functions.prf:
/Qt/5.12.5/static/mkspecs/features/qt_config.prf:
/Qt/5.12.5/static/mkspecs/linux-g++/qmake.conf:
/Qt/5.12.5/static/mkspecs/features/spec_post.prf:
.qmake.stash:
/Qt/5.12.5/static/mkspecs/features/exclusive_builds.prf:
/Qt/5.12.5/static/mkspecs/features/toolchain.prf:
/Qt/5.12.5/static/mkspecs/features/default_pre.prf:
/Qt/5.12.5/static/mkspecs/features/resolve_config.prf:
/Qt/5.12.5/static/mkspecs/features/default_post.prf:
/Qt/5.12.5/static/mkspecs/features/warn_on.prf:
/Qt/5.12.5/static/mkspecs/features/qt.prf:
/Qt/5.12.5/static/mkspecs/features/gc_binaries.prf:
/Qt/5.12.5/static/mkspecs/features/resources.prf:
/Qt/5.12.5/static/mkspecs/features/moc.prf:
/Qt/5.12.5/static/mkspecs/features/unix/opengl.prf:
/Qt/5.12.5/static/mkspecs/features/uic.prf:
/Qt/5.12.5/static/mkspecs/features/unix/thread.prf:
/Qt/5.12.5/static/mkspecs/features/qmake_use.prf:
/Qt/5.12.5/static/mkspecs/features/file_copies.prf:
/Qt/5.12.5/static/mkspecs/features/testcase_targets.prf:
/Qt/5.12.5/static/mkspecs/features/exceptions.prf:
/Qt/5.12.5/static/mkspecs/features/yacc.prf:
/Qt/5.12.5/static/mkspecs/features/lex.prf:
qtrpn.pro:
/Qt/5.12.5/static/plugins/imageformats/libqgif.prl:
/Qt/5.12.5/static/plugins/imageformats/libqicns.prl:
/Qt/5.12.5/static/plugins/imageformats/libqico.prl:
/Qt/5.12.5/static/plugins/imageformats/libqjpeg.prl:
/Qt/5.12.5/static/plugins/imageformats/libqtga.prl:
/Qt/5.12.5/static/plugins/imageformats/libqtiff.prl:
/Qt/5.12.5/static/plugins/imageformats/libqwbmp.prl:
/Qt/5.12.5/static/plugins/imageformats/libqwebp.prl:
/Qt/5.12.5/static/lib/libQt5Widgets.prl:
/Qt/5.12.5/static/lib/libQt5Gui.prl:
/Qt/5.12.5/static/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qtrpn.pro -config release

qmake_all: FORCE


all: Makefile qtrpn

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Qt/5.12.5/static/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h macros.h getcommandline2.h timlibc2.h tokenizec2.h hpcalcc2.h holidaycalc2.h makesubst.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp getcommandline2.cpp timlibc2.cpp tokenizec2.cpp holidaycalc2.cpp hpcalcc2.cpp makesubst.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/rob/qtrpn/qtrpn_plugin_import.cpp .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Qt/5.12.5/static/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -ffunction-sections -fdata-sections -dM -E -o moc_predefs.h /Qt/5.12.5/static/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/Qt/5.12.5/static/include/QtWidgets/QMainWindow \
		/Qt/5.12.5/static/include/QtWidgets/qmainwindow.h \
		/Qt/5.12.5/static/include/QtWidgets/qtwidgetsglobal.h \
		/Qt/5.12.5/static/include/QtGui/qtguiglobal.h \
		/Qt/5.12.5/static/include/QtCore/qglobal.h \
		/Qt/5.12.5/static/include/QtCore/qconfig-bootstrapped.h \
		/Qt/5.12.5/static/include/QtCore/qconfig.h \
		/Qt/5.12.5/static/include/QtCore/qtcore-config.h \
		/Qt/5.12.5/static/include/QtCore/qsystemdetection.h \
		/Qt/5.12.5/static/include/QtCore/qprocessordetection.h \
		/Qt/5.12.5/static/include/QtCore/qcompilerdetection.h \
		/Qt/5.12.5/static/include/QtCore/qtypeinfo.h \
		/Qt/5.12.5/static/include/QtCore/qsysinfo.h \
		/Qt/5.12.5/static/include/QtCore/qlogging.h \
		/Qt/5.12.5/static/include/QtCore/qflags.h \
		/Qt/5.12.5/static/include/QtCore/qatomic.h \
		/Qt/5.12.5/static/include/QtCore/qbasicatomic.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_bootstrap.h \
		/Qt/5.12.5/static/include/QtCore/qgenericatomic.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_cxx11.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_msvc.h \
		/Qt/5.12.5/static/include/QtCore/qglobalstatic.h \
		/Qt/5.12.5/static/include/QtCore/qmutex.h \
		/Qt/5.12.5/static/include/QtCore/qnumeric.h \
		/Qt/5.12.5/static/include/QtCore/qversiontagging.h \
		/Qt/5.12.5/static/include/QtGui/qtgui-config.h \
		/Qt/5.12.5/static/include/QtWidgets/qtwidgets-config.h \
		/Qt/5.12.5/static/include/QtWidgets/qwidget.h \
		/Qt/5.12.5/static/include/QtGui/qwindowdefs.h \
		/Qt/5.12.5/static/include/QtCore/qobjectdefs.h \
		/Qt/5.12.5/static/include/QtCore/qnamespace.h \
		/Qt/5.12.5/static/include/QtCore/qobjectdefs_impl.h \
		/Qt/5.12.5/static/include/QtGui/qwindowdefs_win.h \
		/Qt/5.12.5/static/include/QtCore/qobject.h \
		/Qt/5.12.5/static/include/QtCore/qstring.h \
		/Qt/5.12.5/static/include/QtCore/qchar.h \
		/Qt/5.12.5/static/include/QtCore/qbytearray.h \
		/Qt/5.12.5/static/include/QtCore/qrefcount.h \
		/Qt/5.12.5/static/include/QtCore/qarraydata.h \
		/Qt/5.12.5/static/include/QtCore/qstringliteral.h \
		/Qt/5.12.5/static/include/QtCore/qstringalgorithms.h \
		/Qt/5.12.5/static/include/QtCore/qstringview.h \
		/Qt/5.12.5/static/include/QtCore/qstringbuilder.h \
		/Qt/5.12.5/static/include/QtCore/qlist.h \
		/Qt/5.12.5/static/include/QtCore/qalgorithms.h \
		/Qt/5.12.5/static/include/QtCore/qiterator.h \
		/Qt/5.12.5/static/include/QtCore/qhashfunctions.h \
		/Qt/5.12.5/static/include/QtCore/qpair.h \
		/Qt/5.12.5/static/include/QtCore/qbytearraylist.h \
		/Qt/5.12.5/static/include/QtCore/qstringlist.h \
		/Qt/5.12.5/static/include/QtCore/qregexp.h \
		/Qt/5.12.5/static/include/QtCore/qstringmatcher.h \
		/Qt/5.12.5/static/include/QtCore/qcoreevent.h \
		/Qt/5.12.5/static/include/QtCore/qscopedpointer.h \
		/Qt/5.12.5/static/include/QtCore/qmetatype.h \
		/Qt/5.12.5/static/include/QtCore/qvarlengtharray.h \
		/Qt/5.12.5/static/include/QtCore/qcontainerfwd.h \
		/Qt/5.12.5/static/include/QtCore/qobject_impl.h \
		/Qt/5.12.5/static/include/QtCore/qmargins.h \
		/Qt/5.12.5/static/include/QtGui/qpaintdevice.h \
		/Qt/5.12.5/static/include/QtCore/qrect.h \
		/Qt/5.12.5/static/include/QtCore/qsize.h \
		/Qt/5.12.5/static/include/QtCore/qpoint.h \
		/Qt/5.12.5/static/include/QtGui/qpalette.h \
		/Qt/5.12.5/static/include/QtGui/qcolor.h \
		/Qt/5.12.5/static/include/QtGui/qrgb.h \
		/Qt/5.12.5/static/include/QtGui/qrgba64.h \
		/Qt/5.12.5/static/include/QtGui/qbrush.h \
		/Qt/5.12.5/static/include/QtCore/qvector.h \
		/Qt/5.12.5/static/include/QtGui/qmatrix.h \
		/Qt/5.12.5/static/include/QtGui/qpolygon.h \
		/Qt/5.12.5/static/include/QtGui/qregion.h \
		/Qt/5.12.5/static/include/QtCore/qdatastream.h \
		/Qt/5.12.5/static/include/QtCore/qiodevice.h \
		/Qt/5.12.5/static/include/QtCore/qline.h \
		/Qt/5.12.5/static/include/QtGui/qtransform.h \
		/Qt/5.12.5/static/include/QtGui/qpainterpath.h \
		/Qt/5.12.5/static/include/QtGui/qimage.h \
		/Qt/5.12.5/static/include/QtGui/qpixelformat.h \
		/Qt/5.12.5/static/include/QtGui/qpixmap.h \
		/Qt/5.12.5/static/include/QtCore/qsharedpointer.h \
		/Qt/5.12.5/static/include/QtCore/qshareddata.h \
		/Qt/5.12.5/static/include/QtCore/qhash.h \
		/Qt/5.12.5/static/include/QtCore/qsharedpointer_impl.h \
		/Qt/5.12.5/static/include/QtGui/qfont.h \
		/Qt/5.12.5/static/include/QtGui/qfontmetrics.h \
		/Qt/5.12.5/static/include/QtGui/qfontinfo.h \
		/Qt/5.12.5/static/include/QtWidgets/qsizepolicy.h \
		/Qt/5.12.5/static/include/QtGui/qcursor.h \
		/Qt/5.12.5/static/include/QtGui/qkeysequence.h \
		/Qt/5.12.5/static/include/QtGui/qevent.h \
		/Qt/5.12.5/static/include/QtCore/qvariant.h \
		/Qt/5.12.5/static/include/QtCore/qmap.h \
		/Qt/5.12.5/static/include/QtCore/qdebug.h \
		/Qt/5.12.5/static/include/QtCore/qtextstream.h \
		/Qt/5.12.5/static/include/QtCore/qlocale.h \
		/Qt/5.12.5/static/include/QtCore/qset.h \
		/Qt/5.12.5/static/include/QtCore/qcontiguouscache.h \
		/Qt/5.12.5/static/include/QtCore/qurl.h \
		/Qt/5.12.5/static/include/QtCore/qurlquery.h \
		/Qt/5.12.5/static/include/QtCore/qfile.h \
		/Qt/5.12.5/static/include/QtCore/qfiledevice.h \
		/Qt/5.12.5/static/include/QtGui/qvector2d.h \
		/Qt/5.12.5/static/include/QtGui/qtouchdevice.h \
		/Qt/5.12.5/static/include/QtWidgets/qtabwidget.h \
		/Qt/5.12.5/static/include/QtGui/qicon.h \
		macros.h \
		moc_predefs.h \
		/Qt/5.12.5/static/bin/moc
	/Qt/5.12.5/static/bin/moc $(DEFINES) --include /home/rob/qtrpn/moc_predefs.h -I/Qt/5.12.5/static/mkspecs/linux-g++ -I/home/rob/qtrpn -I/Qt/5.12.5/static/include -I/Qt/5.12.5/static/include/QtWidgets -I/Qt/5.12.5/static/include/QtGui -I/Qt/5.12.5/static/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Qt/5.12.5/static/bin/uic
	/Qt/5.12.5/static/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Qt/5.12.5/static/include/QtWidgets/QMainWindow \
		/Qt/5.12.5/static/include/QtWidgets/qmainwindow.h \
		/Qt/5.12.5/static/include/QtWidgets/qtwidgetsglobal.h \
		/Qt/5.12.5/static/include/QtGui/qtguiglobal.h \
		/Qt/5.12.5/static/include/QtCore/qglobal.h \
		/Qt/5.12.5/static/include/QtCore/qconfig-bootstrapped.h \
		/Qt/5.12.5/static/include/QtCore/qconfig.h \
		/Qt/5.12.5/static/include/QtCore/qtcore-config.h \
		/Qt/5.12.5/static/include/QtCore/qsystemdetection.h \
		/Qt/5.12.5/static/include/QtCore/qprocessordetection.h \
		/Qt/5.12.5/static/include/QtCore/qcompilerdetection.h \
		/Qt/5.12.5/static/include/QtCore/qtypeinfo.h \
		/Qt/5.12.5/static/include/QtCore/qsysinfo.h \
		/Qt/5.12.5/static/include/QtCore/qlogging.h \
		/Qt/5.12.5/static/include/QtCore/qflags.h \
		/Qt/5.12.5/static/include/QtCore/qatomic.h \
		/Qt/5.12.5/static/include/QtCore/qbasicatomic.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_bootstrap.h \
		/Qt/5.12.5/static/include/QtCore/qgenericatomic.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_cxx11.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_msvc.h \
		/Qt/5.12.5/static/include/QtCore/qglobalstatic.h \
		/Qt/5.12.5/static/include/QtCore/qmutex.h \
		/Qt/5.12.5/static/include/QtCore/qnumeric.h \
		/Qt/5.12.5/static/include/QtCore/qversiontagging.h \
		/Qt/5.12.5/static/include/QtGui/qtgui-config.h \
		/Qt/5.12.5/static/include/QtWidgets/qtwidgets-config.h \
		/Qt/5.12.5/static/include/QtWidgets/qwidget.h \
		/Qt/5.12.5/static/include/QtGui/qwindowdefs.h \
		/Qt/5.12.5/static/include/QtCore/qobjectdefs.h \
		/Qt/5.12.5/static/include/QtCore/qnamespace.h \
		/Qt/5.12.5/static/include/QtCore/qobjectdefs_impl.h \
		/Qt/5.12.5/static/include/QtGui/qwindowdefs_win.h \
		/Qt/5.12.5/static/include/QtCore/qobject.h \
		/Qt/5.12.5/static/include/QtCore/qstring.h \
		/Qt/5.12.5/static/include/QtCore/qchar.h \
		/Qt/5.12.5/static/include/QtCore/qbytearray.h \
		/Qt/5.12.5/static/include/QtCore/qrefcount.h \
		/Qt/5.12.5/static/include/QtCore/qarraydata.h \
		/Qt/5.12.5/static/include/QtCore/qstringliteral.h \
		/Qt/5.12.5/static/include/QtCore/qstringalgorithms.h \
		/Qt/5.12.5/static/include/QtCore/qstringview.h \
		/Qt/5.12.5/static/include/QtCore/qstringbuilder.h \
		/Qt/5.12.5/static/include/QtCore/qlist.h \
		/Qt/5.12.5/static/include/QtCore/qalgorithms.h \
		/Qt/5.12.5/static/include/QtCore/qiterator.h \
		/Qt/5.12.5/static/include/QtCore/qhashfunctions.h \
		/Qt/5.12.5/static/include/QtCore/qpair.h \
		/Qt/5.12.5/static/include/QtCore/qbytearraylist.h \
		/Qt/5.12.5/static/include/QtCore/qstringlist.h \
		/Qt/5.12.5/static/include/QtCore/qregexp.h \
		/Qt/5.12.5/static/include/QtCore/qstringmatcher.h \
		/Qt/5.12.5/static/include/QtCore/qcoreevent.h \
		/Qt/5.12.5/static/include/QtCore/qscopedpointer.h \
		/Qt/5.12.5/static/include/QtCore/qmetatype.h \
		/Qt/5.12.5/static/include/QtCore/qvarlengtharray.h \
		/Qt/5.12.5/static/include/QtCore/qcontainerfwd.h \
		/Qt/5.12.5/static/include/QtCore/qobject_impl.h \
		/Qt/5.12.5/static/include/QtCore/qmargins.h \
		/Qt/5.12.5/static/include/QtGui/qpaintdevice.h \
		/Qt/5.12.5/static/include/QtCore/qrect.h \
		/Qt/5.12.5/static/include/QtCore/qsize.h \
		/Qt/5.12.5/static/include/QtCore/qpoint.h \
		/Qt/5.12.5/static/include/QtGui/qpalette.h \
		/Qt/5.12.5/static/include/QtGui/qcolor.h \
		/Qt/5.12.5/static/include/QtGui/qrgb.h \
		/Qt/5.12.5/static/include/QtGui/qrgba64.h \
		/Qt/5.12.5/static/include/QtGui/qbrush.h \
		/Qt/5.12.5/static/include/QtCore/qvector.h \
		/Qt/5.12.5/static/include/QtGui/qmatrix.h \
		/Qt/5.12.5/static/include/QtGui/qpolygon.h \
		/Qt/5.12.5/static/include/QtGui/qregion.h \
		/Qt/5.12.5/static/include/QtCore/qdatastream.h \
		/Qt/5.12.5/static/include/QtCore/qiodevice.h \
		/Qt/5.12.5/static/include/QtCore/qline.h \
		/Qt/5.12.5/static/include/QtGui/qtransform.h \
		/Qt/5.12.5/static/include/QtGui/qpainterpath.h \
		/Qt/5.12.5/static/include/QtGui/qimage.h \
		/Qt/5.12.5/static/include/QtGui/qpixelformat.h \
		/Qt/5.12.5/static/include/QtGui/qpixmap.h \
		/Qt/5.12.5/static/include/QtCore/qsharedpointer.h \
		/Qt/5.12.5/static/include/QtCore/qshareddata.h \
		/Qt/5.12.5/static/include/QtCore/qhash.h \
		/Qt/5.12.5/static/include/QtCore/qsharedpointer_impl.h \
		/Qt/5.12.5/static/include/QtGui/qfont.h \
		/Qt/5.12.5/static/include/QtGui/qfontmetrics.h \
		/Qt/5.12.5/static/include/QtGui/qfontinfo.h \
		/Qt/5.12.5/static/include/QtWidgets/qsizepolicy.h \
		/Qt/5.12.5/static/include/QtGui/qcursor.h \
		/Qt/5.12.5/static/include/QtGui/qkeysequence.h \
		/Qt/5.12.5/static/include/QtGui/qevent.h \
		/Qt/5.12.5/static/include/QtCore/qvariant.h \
		/Qt/5.12.5/static/include/QtCore/qmap.h \
		/Qt/5.12.5/static/include/QtCore/qdebug.h \
		/Qt/5.12.5/static/include/QtCore/qtextstream.h \
		/Qt/5.12.5/static/include/QtCore/qlocale.h \
		/Qt/5.12.5/static/include/QtCore/qset.h \
		/Qt/5.12.5/static/include/QtCore/qcontiguouscache.h \
		/Qt/5.12.5/static/include/QtCore/qurl.h \
		/Qt/5.12.5/static/include/QtCore/qurlquery.h \
		/Qt/5.12.5/static/include/QtCore/qfile.h \
		/Qt/5.12.5/static/include/QtCore/qfiledevice.h \
		/Qt/5.12.5/static/include/QtGui/qvector2d.h \
		/Qt/5.12.5/static/include/QtGui/qtouchdevice.h \
		/Qt/5.12.5/static/include/QtWidgets/qtabwidget.h \
		/Qt/5.12.5/static/include/QtGui/qicon.h \
		macros.h \
		/Qt/5.12.5/static/include/QtWidgets/QApplication \
		/Qt/5.12.5/static/include/QtWidgets/qapplication.h \
		/Qt/5.12.5/static/include/QtCore/qcoreapplication.h \
		/Qt/5.12.5/static/include/QtCore/qeventloop.h \
		/Qt/5.12.5/static/include/QtWidgets/qdesktopwidget.h \
		/Qt/5.12.5/static/include/QtGui/qguiapplication.h \
		/Qt/5.12.5/static/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Qt/5.12.5/static/include/QtWidgets/QMainWindow \
		/Qt/5.12.5/static/include/QtWidgets/qmainwindow.h \
		/Qt/5.12.5/static/include/QtWidgets/qtwidgetsglobal.h \
		/Qt/5.12.5/static/include/QtGui/qtguiglobal.h \
		/Qt/5.12.5/static/include/QtCore/qglobal.h \
		/Qt/5.12.5/static/include/QtCore/qconfig-bootstrapped.h \
		/Qt/5.12.5/static/include/QtCore/qconfig.h \
		/Qt/5.12.5/static/include/QtCore/qtcore-config.h \
		/Qt/5.12.5/static/include/QtCore/qsystemdetection.h \
		/Qt/5.12.5/static/include/QtCore/qprocessordetection.h \
		/Qt/5.12.5/static/include/QtCore/qcompilerdetection.h \
		/Qt/5.12.5/static/include/QtCore/qtypeinfo.h \
		/Qt/5.12.5/static/include/QtCore/qsysinfo.h \
		/Qt/5.12.5/static/include/QtCore/qlogging.h \
		/Qt/5.12.5/static/include/QtCore/qflags.h \
		/Qt/5.12.5/static/include/QtCore/qatomic.h \
		/Qt/5.12.5/static/include/QtCore/qbasicatomic.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_bootstrap.h \
		/Qt/5.12.5/static/include/QtCore/qgenericatomic.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_cxx11.h \
		/Qt/5.12.5/static/include/QtCore/qatomic_msvc.h \
		/Qt/5.12.5/static/include/QtCore/qglobalstatic.h \
		/Qt/5.12.5/static/include/QtCore/qmutex.h \
		/Qt/5.12.5/static/include/QtCore/qnumeric.h \
		/Qt/5.12.5/static/include/QtCore/qversiontagging.h \
		/Qt/5.12.5/static/include/QtGui/qtgui-config.h \
		/Qt/5.12.5/static/include/QtWidgets/qtwidgets-config.h \
		/Qt/5.12.5/static/include/QtWidgets/qwidget.h \
		/Qt/5.12.5/static/include/QtGui/qwindowdefs.h \
		/Qt/5.12.5/static/include/QtCore/qobjectdefs.h \
		/Qt/5.12.5/static/include/QtCore/qnamespace.h \
		/Qt/5.12.5/static/include/QtCore/qobjectdefs_impl.h \
		/Qt/5.12.5/static/include/QtGui/qwindowdefs_win.h \
		/Qt/5.12.5/static/include/QtCore/qobject.h \
		/Qt/5.12.5/static/include/QtCore/qstring.h \
		/Qt/5.12.5/static/include/QtCore/qchar.h \
		/Qt/5.12.5/static/include/QtCore/qbytearray.h \
		/Qt/5.12.5/static/include/QtCore/qrefcount.h \
		/Qt/5.12.5/static/include/QtCore/qarraydata.h \
		/Qt/5.12.5/static/include/QtCore/qstringliteral.h \
		/Qt/5.12.5/static/include/QtCore/qstringalgorithms.h \
		/Qt/5.12.5/static/include/QtCore/qstringview.h \
		/Qt/5.12.5/static/include/QtCore/qstringbuilder.h \
		/Qt/5.12.5/static/include/QtCore/qlist.h \
		/Qt/5.12.5/static/include/QtCore/qalgorithms.h \
		/Qt/5.12.5/static/include/QtCore/qiterator.h \
		/Qt/5.12.5/static/include/QtCore/qhashfunctions.h \
		/Qt/5.12.5/static/include/QtCore/qpair.h \
		/Qt/5.12.5/static/include/QtCore/qbytearraylist.h \
		/Qt/5.12.5/static/include/QtCore/qstringlist.h \
		/Qt/5.12.5/static/include/QtCore/qregexp.h \
		/Qt/5.12.5/static/include/QtCore/qstringmatcher.h \
		/Qt/5.12.5/static/include/QtCore/qcoreevent.h \
		/Qt/5.12.5/static/include/QtCore/qscopedpointer.h \
		/Qt/5.12.5/static/include/QtCore/qmetatype.h \
		/Qt/5.12.5/static/include/QtCore/qvarlengtharray.h \
		/Qt/5.12.5/static/include/QtCore/qcontainerfwd.h \
		/Qt/5.12.5/static/include/QtCore/qobject_impl.h \
		/Qt/5.12.5/static/include/QtCore/qmargins.h \
		/Qt/5.12.5/static/include/QtGui/qpaintdevice.h \
		/Qt/5.12.5/static/include/QtCore/qrect.h \
		/Qt/5.12.5/static/include/QtCore/qsize.h \
		/Qt/5.12.5/static/include/QtCore/qpoint.h \
		/Qt/5.12.5/static/include/QtGui/qpalette.h \
		/Qt/5.12.5/static/include/QtGui/qcolor.h \
		/Qt/5.12.5/static/include/QtGui/qrgb.h \
		/Qt/5.12.5/static/include/QtGui/qrgba64.h \
		/Qt/5.12.5/static/include/QtGui/qbrush.h \
		/Qt/5.12.5/static/include/QtCore/qvector.h \
		/Qt/5.12.5/static/include/QtGui/qmatrix.h \
		/Qt/5.12.5/static/include/QtGui/qpolygon.h \
		/Qt/5.12.5/static/include/QtGui/qregion.h \
		/Qt/5.12.5/static/include/QtCore/qdatastream.h \
		/Qt/5.12.5/static/include/QtCore/qiodevice.h \
		/Qt/5.12.5/static/include/QtCore/qline.h \
		/Qt/5.12.5/static/include/QtGui/qtransform.h \
		/Qt/5.12.5/static/include/QtGui/qpainterpath.h \
		/Qt/5.12.5/static/include/QtGui/qimage.h \
		/Qt/5.12.5/static/include/QtGui/qpixelformat.h \
		/Qt/5.12.5/static/include/QtGui/qpixmap.h \
		/Qt/5.12.5/static/include/QtCore/qsharedpointer.h \
		/Qt/5.12.5/static/include/QtCore/qshareddata.h \
		/Qt/5.12.5/static/include/QtCore/qhash.h \
		/Qt/5.12.5/static/include/QtCore/qsharedpointer_impl.h \
		/Qt/5.12.5/static/include/QtGui/qfont.h \
		/Qt/5.12.5/static/include/QtGui/qfontmetrics.h \
		/Qt/5.12.5/static/include/QtGui/qfontinfo.h \
		/Qt/5.12.5/static/include/QtWidgets/qsizepolicy.h \
		/Qt/5.12.5/static/include/QtGui/qcursor.h \
		/Qt/5.12.5/static/include/QtGui/qkeysequence.h \
		/Qt/5.12.5/static/include/QtGui/qevent.h \
		/Qt/5.12.5/static/include/QtCore/qvariant.h \
		/Qt/5.12.5/static/include/QtCore/qmap.h \
		/Qt/5.12.5/static/include/QtCore/qdebug.h \
		/Qt/5.12.5/static/include/QtCore/qtextstream.h \
		/Qt/5.12.5/static/include/QtCore/qlocale.h \
		/Qt/5.12.5/static/include/QtCore/qset.h \
		/Qt/5.12.5/static/include/QtCore/qcontiguouscache.h \
		/Qt/5.12.5/static/include/QtCore/qurl.h \
		/Qt/5.12.5/static/include/QtCore/qurlquery.h \
		/Qt/5.12.5/static/include/QtCore/qfile.h \
		/Qt/5.12.5/static/include/QtCore/qfiledevice.h \
		/Qt/5.12.5/static/include/QtGui/qvector2d.h \
		/Qt/5.12.5/static/include/QtGui/qtouchdevice.h \
		/Qt/5.12.5/static/include/QtWidgets/qtabwidget.h \
		/Qt/5.12.5/static/include/QtGui/qicon.h \
		macros.h \
		ui_mainwindow.h \
		/Qt/5.12.5/static/include/QtCore/QVariant \
		/Qt/5.12.5/static/include/QtWidgets/QAction \
		/Qt/5.12.5/static/include/QtWidgets/qaction.h \
		/Qt/5.12.5/static/include/QtWidgets/qactiongroup.h \
		/Qt/5.12.5/static/include/QtWidgets/QApplication \
		/Qt/5.12.5/static/include/QtWidgets/qapplication.h \
		/Qt/5.12.5/static/include/QtCore/qcoreapplication.h \
		/Qt/5.12.5/static/include/QtCore/qeventloop.h \
		/Qt/5.12.5/static/include/QtWidgets/qdesktopwidget.h \
		/Qt/5.12.5/static/include/QtGui/qguiapplication.h \
		/Qt/5.12.5/static/include/QtGui/qinputmethod.h \
		/Qt/5.12.5/static/include/QtWidgets/QButtonGroup \
		/Qt/5.12.5/static/include/QtWidgets/qbuttongroup.h \
		/Qt/5.12.5/static/include/QtWidgets/QHBoxLayout \
		/Qt/5.12.5/static/include/QtWidgets/qboxlayout.h \
		/Qt/5.12.5/static/include/QtWidgets/qlayout.h \
		/Qt/5.12.5/static/include/QtWidgets/qlayoutitem.h \
		/Qt/5.12.5/static/include/QtWidgets/qgridlayout.h \
		/Qt/5.12.5/static/include/QtWidgets/QHeaderView \
		/Qt/5.12.5/static/include/QtWidgets/qheaderview.h \
		/Qt/5.12.5/static/include/QtWidgets/qabstractitemview.h \
		/Qt/5.12.5/static/include/QtWidgets/qabstractscrollarea.h \
		/Qt/5.12.5/static/include/QtWidgets/qframe.h \
		/Qt/5.12.5/static/include/QtCore/qabstractitemmodel.h \
		/Qt/5.12.5/static/include/QtCore/qitemselectionmodel.h \
		/Qt/5.12.5/static/include/QtWidgets/qabstractitemdelegate.h \
		/Qt/5.12.5/static/include/QtWidgets/qstyleoption.h \
		/Qt/5.12.5/static/include/QtWidgets/qabstractspinbox.h \
		/Qt/5.12.5/static/include/QtGui/qvalidator.h \
		/Qt/5.12.5/static/include/QtCore/qregularexpression.h \
		/Qt/5.12.5/static/include/QtWidgets/qslider.h \
		/Qt/5.12.5/static/include/QtWidgets/qabstractslider.h \
		/Qt/5.12.5/static/include/QtWidgets/qstyle.h \
		/Qt/5.12.5/static/include/QtWidgets/qtabbar.h \
		/Qt/5.12.5/static/include/QtWidgets/qrubberband.h \
		/Qt/5.12.5/static/include/QtWidgets/QLabel \
		/Qt/5.12.5/static/include/QtWidgets/qlabel.h \
		/Qt/5.12.5/static/include/QtWidgets/QLineEdit \
		/Qt/5.12.5/static/include/QtWidgets/qlineedit.h \
		/Qt/5.12.5/static/include/QtGui/qtextcursor.h \
		/Qt/5.12.5/static/include/QtGui/qtextformat.h \
		/Qt/5.12.5/static/include/QtGui/qpen.h \
		/Qt/5.12.5/static/include/QtGui/qtextoption.h \
		/Qt/5.12.5/static/include/QtWidgets/QListWidget \
		/Qt/5.12.5/static/include/QtWidgets/qlistwidget.h \
		/Qt/5.12.5/static/include/QtWidgets/qlistview.h \
		/Qt/5.12.5/static/include/QtWidgets/QMenu \
		/Qt/5.12.5/static/include/QtWidgets/qmenu.h \
		/Qt/5.12.5/static/include/QtWidgets/QMenuBar \
		/Qt/5.12.5/static/include/QtWidgets/qmenubar.h \
		/Qt/5.12.5/static/include/QtWidgets/QPushButton \
		/Qt/5.12.5/static/include/QtWidgets/qpushbutton.h \
		/Qt/5.12.5/static/include/QtWidgets/qabstractbutton.h \
		/Qt/5.12.5/static/include/QtWidgets/QSpacerItem \
		/Qt/5.12.5/static/include/QtWidgets/QStatusBar \
		/Qt/5.12.5/static/include/QtWidgets/qstatusbar.h \
		/Qt/5.12.5/static/include/QtWidgets/QVBoxLayout \
		/Qt/5.12.5/static/include/QtWidgets/QWidget \
		/Qt/5.12.5/static/include/QtCore/QFile \
		/Qt/5.12.5/static/include/QtWidgets/QFileDialog \
		/Qt/5.12.5/static/include/QtWidgets/qfiledialog.h \
		/Qt/5.12.5/static/include/QtCore/qdir.h \
		/Qt/5.12.5/static/include/QtCore/qfileinfo.h \
		/Qt/5.12.5/static/include/QtWidgets/qdialog.h \
		/Qt/5.12.5/static/include/QtCore/QDataStream \
		/Qt/5.12.5/static/include/QtWidgets/QMessageBox \
		/Qt/5.12.5/static/include/QtWidgets/qmessagebox.h \
		/Qt/5.12.5/static/include/QtWidgets/QDialog \
		/Qt/5.12.5/static/include/QtWidgets/QInputDialog \
		/Qt/5.12.5/static/include/QtWidgets/qinputdialog.h \
		/Qt/5.12.5/static/include/QtCore/QDir \
		hpcalcc2.h \
		timlibc2.h \
		tokenizec2.h \
		holidaycalc2.h \
		getcommandline2.h \
		makesubst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

getcommandline2.o: getcommandline2.cpp getcommandline2.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getcommandline2.o getcommandline2.cpp

timlibc2.o: timlibc2.cpp timlibc2.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timlibc2.o timlibc2.cpp

tokenizec2.o: tokenizec2.cpp tokenizec2.h \
		macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tokenizec2.o tokenizec2.cpp

holidaycalc2.o: holidaycalc2.cpp holidaycalc2.h \
		macros.h \
		timlibc2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o holidaycalc2.o holidaycalc2.cpp

hpcalcc2.o: hpcalcc2.cpp macros.h \
		getcommandline2.h \
		timlibc2.h \
		tokenizec2.h \
		hpcalcc2.h \
		holidaycalc2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hpcalcc2.o hpcalcc2.cpp

makesubst.o: makesubst.cpp macros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o makesubst.o makesubst.cpp

qtrpn_plugin_import.o: /home/rob/qtrpn/qtrpn_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtrpn_plugin_import.o /home/rob/qtrpn/qtrpn_plugin_import.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/qtrpn/bin || mkdir -p $(INSTALL_ROOT)/opt/qtrpn/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/qtrpn/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/qtrpn/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/qtrpn/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qtrpn/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

